FROM node:18-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package.json yarn.lock ./
RUN corepack enable && yarn install --frozen-lockfile --production

COPY server ./server

EXPOSE 8787

CMD ["node", "server/index.js"]
